apiVersion: v1
kind: ConfigMap
metadata:
  name: webdb-config
data:
  web.tempHeader: Temperature
  web.pressureHeader: Pressure
  web.bannerTextColor: DarkSlateGray
  web.bannerText: Sensor Database
