apiVersion: v1
kind: ConfigMap
metadata:
  name: webdb-config
data:
  web.tempHeader: Temperature
  web.pressureHeader: Pressure
  web.bannerTextColor: DarkCyan
  web.bannerText: Tanzu Sensor Database
