apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: webdb
spec:
  virtualhost:
    fqdn: default.example.com
    tls:
      secretName: projectcontour/contour-tls
  routes:
    - services:
        - name: webdb
          port: 80
