apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - httpproxy.yaml
  - mysql.yaml
configMapGenerator:
  - name: webdb-config
    literals:
      - spring.datasource.url="jdbc:mysql://sensordb-mysql/sensors"
      - spring.datasource.username=sensors
      - spring.datasource.password=sensors
      - management.metrics.export.wavefront.uri=https://surf.wavefront.com
      - management.metrics.export.wavefront.api-token=a02e7c33-cf9e-4fb5-ac2c-90859476d12f