---
# Source: mysql/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sensordb-mysql
  labels:
    app: mysql
    chart: mysql-6.14.11
    release: "sensordb"
    heritage: "Helm"
secrets:
  - name: sensordb-mysql
---
# Source: mysql/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: sensordb-mysql
  labels:
    app: mysql
    chart: mysql-6.14.11
    release: sensordb
    heritage: Helm
type: Opaque
data:
  mysql-root-password: "cGV0Y2xpbmlj"
  mysql-password: "cGV0Y2xpbmlj"
---
# Source: mysql/templates/master-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: sensordb-mysql-master
  labels:
    app: mysql
    chart: mysql-6.14.11
    release: sensordb
    heritage: Helm
    component: master
data:
  my.cnf: |-
    [mysqld]
    default_authentication_plugin=mysql_native_password
    skip-name-resolve
    explicit_defaults_for_timestamp
    basedir=/opt/bitnami/mysql
    plugin_dir=/opt/bitnami/mysql/plugin
    port=3306
    socket=/opt/bitnami/mysql/tmp/mysql.sock
    datadir=/bitnami/mysql/data
    tmpdir=/opt/bitnami/mysql/tmp
    max_allowed_packet=16M
    bind-address=0.0.0.0
    pid-file=/opt/bitnami/mysql/tmp/mysqld.pid
    log-error=/opt/bitnami/mysql/logs/mysqld.log
    character-set-server=UTF8
    collation-server=utf8_general_ci

    [client]
    port=3306
    socket=/opt/bitnami/mysql/tmp/mysql.sock
    default-character-set=UTF8
    plugin_dir=/opt/bitnami/mysql/plugin

    [manager]
    port=3306
    socket=/opt/bitnami/mysql/tmp/mysql.sock
    pid-file=/opt/bitnami/mysql/tmp/mysqld.pid
---
# Source: mysql/templates/master-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: sensordb-mysql
  labels:
    app: mysql
    chart: mysql-6.14.11
    release: sensordb
    heritage: Helm
    component: master
  annotations:
    prometheus.io/port: '9104'
    prometheus.io/scrape: "true"
spec:
  type: ClusterIP
  ports:
    - name: mysql
      port: 3306
      targetPort: mysql
      nodePort: null
  selector:
    app: mysql
    release: sensordb
    component: master
---
# Source: mysql/templates/master-statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sensordb-mysql-master
  labels:
    app: mysql
    chart: mysql-6.14.11
    release: sensordb
    heritage: Helm
    component: master
spec:
  selector:
    matchLabels:
      app: mysql
      release: sensordb
      component: master
  serviceName: sensordb-mysql-master
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mysql
        chart: mysql-6.14.11
        release: sensordb
        heritage: Helm
        component: master
    spec:
      securityContext:
        fsGroup: 1001
        runAsUser: 1001
      serviceAccountName: sensordb-mysql
      containers:
        - name: mysql
          image: docker.io/bitnami/mysql:8.0.22-debian-10-r0
          imagePullPolicy: "IfNotPresent"
          env:
            - name: BITNAMI_DEBUG
              value: "false"
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sensordb-mysql
                  key: mysql-root-password
            - name: MYSQL_USER
              value: "petclinic"
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sensordb-mysql
                  key: mysql-password
            - name: MYSQL_DATABASE
              value: "petclinic"
          ports:
            - name: mysql
              containerPort: 3306
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - |
                  password_aux="${MYSQL_ROOT_PASSWORD:-}"
                  if [ -f "${MYSQL_ROOT_PASSWORD_FILE:-}" ]; then
                      password_aux=$(cat $MYSQL_ROOT_PASSWORD_FILE)
                  fi
                  mysqladmin status -uroot -p$password_aux
            initialDelaySeconds: 120
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - |
                  password_aux="${MYSQL_ROOT_PASSWORD:-}"
                  if [ -f "${MYSQL_ROOT_PASSWORD_FILE:-}" ]; then
                      password_aux=$(cat $MYSQL_ROOT_PASSWORD_FILE)
                  fi
                  mysqladmin status -uroot -p$password_aux
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          resources:
            limits: {}
            requests: {}
          volumeMounts:
            - name: data
              mountPath: /bitnami/mysql
            - name: config
              mountPath: /opt/bitnami/mysql/conf/my.cnf
              subPath: my.cnf
      volumes:
        - name: config
          configMap:
            name: sensordb-mysql-master
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          app: mysql
          component: master
          release: sensordb
          heritage: Helm
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "8Gi"
